apiVersion: v1
kind: Service
metadata:
  name: mongodb-h
  labels:
    version: v1
    app: mongodb
spec:
  selector:
    app: mongodb
  type: ClusterIP
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
      protocol: TCP