apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    name: mongodb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb-container
          image: mongo
          ports:
          - name: mongo
            containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: db-storage
      volumes:
        - name: db-storage
          emptyDir:
            medium: Memory
  