apiVersion: v1
kind: Service
metadata:
  name: transaction-svc
spec:
  selector:
    app: transaction-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32002
  type: NodePort