apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-api
  labels:
    app: transaction-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-api
  template:
    metadata:
      labels:
        app: "transaction-api"
    spec:
      containers:
      - name: transaction-api
        image: "wesleyguimaraes/transactionsapi"
        ports:
          - containerPort: 8080
        env:
        - name: "SPRING_DATASOURCE_URL"
          value: "mongodb://mongodb-h:27017/transactiondb"